baseURL = 'https://vennylaras.github.io'
languageCode = 'en-us'
title = 'Venny Ayudiani'
paginate = 3
theme = 'maverick'

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "A Landing Page"
  author = 'Venny Ayudiani'

  # [params.comments]
  #   githubRepo = 'canhtran/maverick'
  #   theme = 'github-light'


[menu]
  [[menu.main]]
    identifier = "software"
    name = "Software"
    url = "/software/"
    weight = "-110"
  [[menu.main]]
    identifier = "data"
    name = "Data"
    url = "/data/"
    weight = -200

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
